<?php require __DIR__ . '/../../layouts/header.php'; ?>
<div class="toolbar"><div><h1 class="page-title">Parámetros MG</h1><p class="subtitle">Valores configurables con fuente y estado de evidencia.</p></div></div>
<div class="card"><div class="card-body"><div class="table-wrap"><table class="table"><thead><tr><th>Clave</th><th>Valor</th><th>Descripción</th><th>Fuente</th><th>Evidencia</th><th>Acción</th></tr></thead><tbody>
<?php foreach ($parametros as $p): $modalId='modal-parametro-'.md5($p['clave']); ?>
<tr><td><code><?= e($p['clave']) ?></code></td><td><?= e($p['valor'] ?? '') ?></td><td><?= e($p['descripcion']) ?></td><td><?= e($p['fuente'] ?? '') ?></td><td><?= e($p['estado_evidencia']) ?></td><td><?php if (tiene_permiso('mg.parametros.editar')): ?><button type="button" class="btn btn-primary btn-sm" data-open-modal="#<?=e($modalId)?>">Editar</button><?php else: ?><span class="text-muted">Solo lectura</span><?php endif; ?></td></tr>
<?php endforeach; ?></tbody></table></div></div></div>
<?php if (tiene_permiso('mg.parametros.editar')): foreach ($parametros as $p): $modalId='modal-parametro-'.md5($p['clave']); ?>
<div class="modal" id="<?=e($modalId)?>" role="dialog" aria-modal="true" aria-labelledby="titulo-<?=e($modalId)?>"><div class="modal-dialog"><div class="modal-header"><div><h2 id="titulo-<?=e($modalId)?>">Editar parámetro</h2><div style="opacity:.82;font-size:.78rem"><?=e($p['clave'])?></div></div><button type="button" class="modal-close" data-modal-close aria-label="Cerrar">×</button></div><div class="modal-body"><form method="post" action="/controllers/mg_parametros.php?accion=guardar" class="mg-modal-form" data-no-ajax="1"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="clave" value="<?=e($p['clave'])?>"><div class="form-group"><label class="form-label">Valor</label><input name="valor" value="<?=e($p['valor'] ?? '')?>" required></div><div class="form-group"><label class="form-label">Descripción</label><div class="mg-modal-help"><?=e($p['descripcion'])?></div></div><div class="mg-modal-actions"><button type="button" class="btn btn-light" data-modal-close>Cancelar</button><button class="btn btn-primary" type="submit">Guardar</button></div></form></div></div></div>
<?php endforeach; endif; ?>
<?php require __DIR__ . '/../../layouts/footer.php'; ?>
