<?php
declare(strict_types=1);
require_once __DIR__.'/../config/conexion.php';require_once __DIR__.'/../includes/seguridad.php';require_once __DIR__.'/../includes/permisos.php';require_once __DIR__.'/../models/MgExpedienteModel.php';require_once __DIR__.'/../models/MgAsignacionTutorModel.php';require_once __DIR__.'/../models/MgDocumentoModel.php';require_once __DIR__.'/../models/MgBitacoraModel.php';
require_role(['administrador','coordinador_mg','auxiliar_mg','docente','estudiante']);requerir_permiso('mg.documentos.ver');
$id=(int)($_GET['id_expediente']??$_GET['id']??$_POST['id_expediente']??0);$em=new MgExpedienteModel($pdo);$x=$em->obtener($id);if(!$x)redir('/controllers/mg_expedientes.php?accion=listar');
$rol=user_role();if($rol==='estudiante'&&(int)$x['id_usuario_estudiante']!==(int)$_SESSION['id_usuario'])redir('/views/errores/acceso_denegado.php');if($rol==='docente'){ $sOwn=$pdo->prepare('SELECT COUNT(*) FROM asignaciones_tutor a JOIN tutores t ON t.id_tutor=a.id_tutor JOIN profesores p ON p.id_profesor=t.id_profesor WHERE a.id_expediente=? AND a.estado="vigente" AND p.id_usuario=?');$sOwn->execute([$id,$_SESSION['id_usuario']]);if(!(int)$sOwn->fetchColumn())redir('/views/errores/acceso_denegado.php');}
$am=new MgAsignacionTutorModel($pdo);$t=$am->vigente($id);$dm=new MgDocumentoModel($pdo);
if(($_GET['accion']??'')==='generar'&&$_SERVER['REQUEST_METHOD']==='POST'){requerir_permiso('mg.documentos.generar');validar_csrf();if(!$t){flash('error','El expediente no tiene Tutor vigente.');redir('/controllers/mg_expedientes.php?accion=ficha&id='.$id);}try{$plant=$dm->plantilla('CARTA_ASIGNACION_TUTOR');if(!$plant)throw new RuntimeException('No existe la plantilla activa.');$num=$dm->numero('CARTA_ASIGNACION_TUTOR');$s=$pdo->prepare('SELECT p.id_usuario FROM tutores tt JOIN profesores p ON p.id_profesor=tt.id_profesor WHERE tt.id_tutor=?');$s->execute([$t['id_tutor']]);$tu=$s->fetchColumn();$vars=['estudiante_nombre'=>$x['nombre'].' '.$x['apellido'],'registro_universitario'=>$x['registro_universitario'],'carrera'=>$x['nombre_carrera'],'modalidad'=>$x['modalidad_nombre'],'tema'=>$x['titulo_trabajo']??'','tutor_nombre'=>$t['nombre'].' '.$t['apellido'],'numero_carta'=>$num,'fecha_larga'=>date('d/m/Y'),'cohorte'=>$x['cohorte_nombre']];$html=$plant['cuerpo_html'];foreach($vars as $k=>$v)$html=str_replace('{{'.$k.'}}',e((string)$v),$html);$html=preg_replace('/\{\{[^}]+\}\}/','',$html)??$html;$html='<section>'.$html.'</section><div style="page-break-before:always"></div><section>'.$html.'</section>';$doc=$dm->guardar(['id_plantilla'=>$plant['id_plantilla'],'tipo'=>'CARTA_ASIGNACION_TUTOR','id_expediente'=>$id,'destinatario'=>$t['nombre'].' '.$t['apellido'],'numero'=>$num,'contenido'=>$html]);$bit=new MgBitacoraModel($pdo);$s=$pdo->prepare('UPDATE asignaciones_tutor SET numero_carta=? WHERE id_asignacion=?');$s->execute([$num,$t['id_asignacion']]);$bit->registrar('generar_carta_tutor','documentos_generados',$doc,null,['numero'=>$num,'id_expediente'=>$id]);flash('success','Carta generada con número '.$num.'.');redir('/controllers/mg_documentos.php?accion=ver&id='.$doc);}catch(Throwable $e){flash('error','No se pudo generar la carta: '.$e->getMessage());redir('/controllers/mg_expedientes.php?accion=ficha&id='.$id);}}
if(($_GET['accion']??'')==='ver'){$docId=(int)($_GET['id']??0);$s=$pdo->prepare('SELECT * FROM documentos_generados WHERE id=? AND id_expediente=?');$s->execute([$docId,$id]);$doc=$s->fetch();if(!$doc){flash('error','Documento no encontrado.');redir('/controllers/mg_expedientes.php?accion=ficha&id='.$id);}require __DIR__.'/../views/mg/documentos/ver.php';exit;}
$documentos=$dm->listar($id);$tituloPagina='Documentos del expediente';require __DIR__.'/../views/mg/documentos/index.php';
