<?php
declare(strict_types=1);
require_once __DIR__.'/../config/conexion.php';require_once __DIR__.'/../includes/seguridad.php';require_once __DIR__.'/../includes/permisos.php';require_once __DIR__.'/../models/MgExpedienteModel.php';require_once __DIR__.'/../models/MgBitacoraModel.php';
require_role(['administrador','coordinador_mg','auxiliar_mg','docente','estudiante']);requerir_permiso('mg.expedientes.ver');
$accion=$_GET['accion']??'listar';$model=new MgExpedienteModel($pdo);$bit=new MgBitacoraModel($pdo);$rol=user_role();
if($accion==='guardar'&&$_SERVER['REQUEST_METHOD']==='POST'){requerir_permiso('mg.expedientes.crear');validar_csrf();try{$id=$model->crear(['id_estudiante'=>(int)$_POST['id_estudiante'],'id_modalidad'=>(int)$_POST['id_modalidad'],'id_cohorte'=>(int)$_POST['id_cohorte'],'titulo_trabajo'=>trim((string)$_POST['titulo_trabajo']),'fecha_inicio'=>trim((string)$_POST['fecha_inicio']),'observaciones'=>trim((string)$_POST['observaciones'])]);$bit->registrar('crear_expediente','expedientes_mg',$id,null,$model->obtener($id));flash('success','Expediente creado.');}catch(Throwable $e){flash('error','No se pudo crear el expediente. Verifica estudiante, modalidad y cohorte.');}redir('/controllers/mg_expedientes.php?accion=listar');}
if($accion==='mg2'&&$_SERVER['REQUEST_METHOD']==='POST'){requerir_permiso('mg.expedientes.editar');validar_csrf();$id=(int)$_POST['id_expediente'];$antes=$model->obtener($id);try{$model->cambiarEtapaMg2($id,(string)$_POST['fecha'],trim((string)$_POST['resultado']));$bit->registrar('ingreso_mg2','expedientes_mg',$id,$antes,$model->obtener($id));flash('success','Ingreso a MG2 registrado conservando el historial.');}catch(Throwable $e){flash('error',$e->getMessage());}redir('/controllers/mg_expedientes.php?accion=ficha&id='.$id);}
if($accion==='estado'&&$_SERVER['REQUEST_METHOD']==='POST'){requerir_permiso('mg.expedientes.editar');validar_csrf();$id=(int)$_POST['id_expediente'];$estado=(string)$_POST['estado'];$motivo=trim((string)$_POST['motivo']);if(in_array($estado,['abandono','reprobado'],true)&&$motivo===''){flash('error','Para abandono o reprobado debes registrar motivo.');}else{$antes=$model->obtener($id);$model->cambiarEstado($id,$estado,$motivo);$bit->registrar('cambiar_estado_expediente','expedientes_mg',$id,$antes,$model->obtener($id));flash('success','Estado actualizado.');}redir('/controllers/mg_expedientes.php?accion=ficha&id='.$id);}
if($accion==='ficha'){$id=(int)$_GET['id'];$x=$model->obtener($id);if(!$x) {flash('error','Expediente no encontrado.');redir('/controllers/mg_expedientes.php?accion=listar');}if($rol==='estudiante'&&(int)$x['id_usuario_estudiante']!==(int)$_SESSION['id_usuario'])redir('/views/errores/acceso_denegado.php');if($rol==='docente'){ $s=$pdo->prepare('SELECT COUNT(*) FROM asignaciones_tutor a JOIN tutores t ON t.id_tutor=a.id_tutor JOIN profesores p ON p.id_profesor=t.id_profesor WHERE a.id_expediente=? AND p.id_usuario=? AND a.estado="vigente"');$s->execute([$id,$_SESSION['id_usuario']]);if(!(int)$s->fetchColumn())redir('/views/errores/acceso_denegado.php');}$etapas=$model->etapas($id);$tituloPagina='Expediente MG';require __DIR__.'/../views/mg/expedientes/ficha.php';exit;}
$filtros=['q'=>trim((string)($_GET['q']??'')),'id_cohorte'=>(int)($_GET['id_cohorte']??0),'id_modalidad'=>(int)($_GET['id_modalidad']??0),'etapa_actual'=>trim((string)($_GET['etapa_actual']??'')),'estado'=>trim((string)($_GET['estado']??''))];if($rol==='estudiante'){$s=$pdo->prepare('SELECT id_estudiante FROM estudiantes WHERE id_usuario=?');$s->execute([$_SESSION['id_usuario']]);$idEst=(int)$s->fetchColumn();$filtros['q']=(string)$idEst;/* restricción adicional en consulta abajo */}
$pagina=max(1,(int)($_GET['pagina']??1));
$datos=$model->listar($filtros,$pagina,20);
if($rol==='estudiante'){
 $s=$pdo->prepare('SELECT x.*,e.registro_universitario,u.nombre,u.apellido,m.nombre AS modalidad_nombre,c.nombre AS cohorte_nombre FROM expedientes_mg x JOIN estudiantes e ON e.id_estudiante=x.id_estudiante JOIN usuarios u ON u.id_usuario=e.id_usuario JOIN modalidades_grado m ON m.id_modalidad=x.id_modalidad JOIN cohortes_mg c ON c.id_cohorte=x.id_cohorte WHERE e.id_usuario=? ORDER BY x.fecha_inicio DESC');
 $s->execute([$_SESSION['id_usuario']]);$datos['filas']=$s->fetchAll();$datos['total']=count($datos['filas']);$datos['paginas']=1;
} elseif($rol==='docente'){
 $s=$pdo->prepare('SELECT x.*,e.registro_universitario,u.nombre,u.apellido,m.nombre AS modalidad_nombre,c.nombre AS cohorte_nombre,(SELECT CONCAT(ut.nombre," ",ut.apellido) FROM usuarios ut JOIN profesores pp ON pp.id_usuario=ut.id_usuario JOIN tutores tt ON tt.id_profesor=pp.id_profesor JOIN asignaciones_tutor aa ON aa.id_tutor=tt.id_tutor WHERE aa.id_expediente=x.id_expediente AND aa.estado="vigente" LIMIT 1) AS tutor_nombre FROM expedientes_mg x JOIN estudiantes e ON e.id_estudiante=x.id_estudiante JOIN usuarios u ON u.id_usuario=e.id_usuario JOIN modalidades_grado m ON m.id_modalidad=x.id_modalidad JOIN cohortes_mg c ON c.id_cohorte=x.id_cohorte JOIN asignaciones_tutor own ON own.id_expediente=x.id_expediente AND own.estado="vigente" JOIN tutores ot ON ot.id_tutor=own.id_tutor JOIN profesores op ON op.id_profesor=ot.id_profesor WHERE op.id_usuario=? ORDER BY x.fecha_inicio DESC');
 $s->execute([$_SESSION['id_usuario']]);$datos['filas']=$s->fetchAll();$datos['total']=count($datos['filas']);$datos['paginas']=1;
}
$cohortes=$model->cohortes();$modalidades=$model->modalidades();$puedeCrear=tiene_permiso('mg.expedientes.crear');$tituloPagina='Expedientes MG';require __DIR__.'/../views/mg/expedientes/index.php';
