<?php require __DIR__ . '/../../layouts/header.php'; ?>
<div class="toolbar">
<div><h1 class="page-title">Calendario MG</h1><p class="subtitle">Hitos configurables por cohorte; la cantidad de informes se obtiene de los hitos tipo informe.</p></div>
<?php if ($puedeEditar && $cohortes): ?><button type="button" class="btn btn-primary" data-open-modal="#modal-nuevo-hito"><i class="bi bi-plus-circle" aria-hidden="true"></i> Agregar hito</button><?php endif; ?>
</div>
<div class="card"><div class="card-body">
<form method="get" class="filter-form"><input type="hidden" name="accion" value="listar"><div class="form-group"><label class="form-label">Cohorte</label><select name="id_cohorte" onchange="this.form.submit()"><option value="">Todas</option><?php foreach ($cohortes as $c): ?><option value="<?= (int)$c['id_cohorte'] ?>" <?= $idCohorte===(int)$c['id_cohorte']?'selected':'' ?>><?= e($c['nombre']) ?></option><?php endforeach; ?></select></div></form>
<div class="table-wrap"><table class="table"><thead><tr><th>Cohorte</th><th>Etapa</th><th>Tipo</th><th>Nombre</th><th>Orden</th><th>Límite</th><th>Avance esperado</th><th></th></tr></thead><tbody>
<?php foreach ($hitos as $h): ?><tr><td><?= e($h['cohorte_nombre']) ?></td><td><?= e($h['etapa']) ?></td><td><?= e($h['tipo']) ?></td><td><?= e($h['nombre']) ?></td><td><?= (int)$h['orden'] ?></td><td><?= e($h['fecha_limite'] ?? '') ?></td><td><?= $h['avance_esperado_pct'] === null ? '—' : (int)$h['avance_esperado_pct'].'%' ?></td><td><?php if ($puedeEditar): ?><form method="post" action="/controllers/mg_calendario.php?accion=eliminar" class="inline-form"><input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>"><input type="hidden" name="id_hito" value="<?= (int)$h['id_hito'] ?>"><button class="btn btn-light btn-sm" type="submit" data-confirm="¿Eliminar este hito del calendario MG?">Eliminar</button></form><?php endif; ?></td></tr><?php endforeach; ?>
<?php if (!$hitos): ?><tr><td colspan="8" class="empty compact">No hay hitos cargados para el filtro seleccionado.</td></tr><?php endif; ?></tbody></table></div></div></div>
<?php if ($puedeEditar && $cohortes): ?>
<div class="modal mg-modal-wide" id="modal-nuevo-hito" role="dialog" aria-modal="true" aria-labelledby="titulo-nuevo-hito"><div class="modal-dialog"><div class="modal-header"><h2 id="titulo-nuevo-hito">Agregar hito al calendario</h2><button type="button" class="modal-close" data-modal-close aria-label="Cerrar">×</button></div><div class="modal-body"><form method="post" action="/controllers/mg_calendario.php?accion=guardar" class="mg-modal-form" data-no-ajax="1"><input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>"><div class="grid grid-2"><div class="form-group"><label class="form-label">Cohorte</label><select name="id_cohorte" required><?php foreach($cohortes as $c): ?><option value="<?= (int)$c['id_cohorte'] ?>" <?= $idCohorte===(int)$c['id_cohorte']?'selected':'' ?>><?= e($c['nombre']) ?></option><?php endforeach; ?></select></div><div class="form-group"><label class="form-label">Etapa</label><select name="etapa"><option value="previa">Previa</option><option value="mg1">MG1</option><option value="mg2">MG2</option></select></div><div class="form-group"><label class="form-label">Tipo</label><select name="tipo"><?php foreach(['taller','asignacion_tutor','asignacion_tribunal','informe','defensa','ingreso_mg2','otro'] as $tipo): ?><option value="<?= e($tipo) ?>"><?= e($tipo) ?></option><?php endforeach; ?></select></div><div class="form-group"><label class="form-label">Nombre</label><input name="nombre" required></div><div class="form-group"><label class="form-label">Orden</label><input type="number" name="orden" min="1" value="1"></div><div class="form-group"><label class="form-label">Fecha límite</label><input type="date" name="fecha_limite"></div><div class="form-group"><label class="form-label">Avance esperado % (opcional)</label><input type="number" name="avance_esperado_pct" min="0" max="100"></div></div><div class="mg-modal-actions"><button type="button" class="btn btn-light" data-modal-close>Cancelar</button><button class="btn btn-primary" type="submit">Guardar hito</button></div></form></div></div></div>
<?php endif; ?>
<?php require __DIR__ . '/../../layouts/footer.php'; ?>
