<?php require __DIR__.'/../../layouts/header.php'; ?>
<div class="toolbar"><div><h1 class="page-title">Expediente #<?=$x['id_expediente']?></h1><p class="subtitle"><?=e($x['apellido'].', '.$x['nombre'])?> · <?=e($x['modalidad_nombre'])?> · <?=e($x['cohorte_nombre'])?></p></div></div>
<div class="card"><div class="card-body"><h2>Datos</h2><p><strong>Registro:</strong> <?=e($x['registro_universitario'])?> · <strong>Carrera:</strong> <?=e($x['nombre_carrera'])?></p><p><strong>Situación académica:</strong> <?=e($x['estado_academico'] ?? 'egresado') ?> · <strong>Etapa:</strong> <?=e($x['etapa_actual'])?> · <strong>Estado:</strong> <?=e($x['estado'])?></p><p><strong>Título:</strong> <?=e($x['titulo_trabajo']??'')?></p><p><?=nl2br(e($x['observaciones']??''))?></p></div></div>
<div class="card"><div class="card-body"><h2>Etapas</h2><div class="table-wrap"><table class="table"><tr><th>Etapa</th><th>Inicio</th><th>Fin</th><th>Resultado</th></tr><?php foreach($etapas as $e): ?><tr><td><?=e($e['etapa'])?></td><td><?=e($e['fecha_inicio'])?></td><td><?=e($e['fecha_fin']??'')?></td><td><?=e($e['resultado']??'')?></td></tr><?php endforeach;?></table></div></div></div>
<div class="card"><div class="card-body"><h2>Tutor</h2><?php require __DIR__.'/../asignaciones/bloque.php'; ?></div></div>
<div class="card"><div class="card-body"><h2>Documentos</h2><a class="btn btn-light" href="/controllers/mg_documentos.php?accion=listar&id_expediente=<?=$x['id_expediente']?>">Ver documentos y cartas</a> <?php if(tiene_permiso('mg.reportes.estudiante')):?><a class="btn btn-light" href="/controllers/mg_reporte_estudiante.php?id_expediente=<?=$x['id_expediente']?>">Reporte imprimible</a><?php endif;?></div></div>
<?php if(tiene_permiso('mg.expedientes.editar')&&$x['etapa_actual']==='mg1'): ?><div class="toolbar" style="margin-top:18px"><div><strong>Continuar proceso</strong><div class="subtitle">Registrar el ingreso formal a MG2.</div></div><button type="button" class="btn btn-primary" data-open-modal="#modal-mg2">Registrar ingreso a MG2</button></div>
<div class="modal" id="modal-mg2" role="dialog" aria-modal="true" aria-labelledby="titulo-mg2"><div class="modal-dialog"><div class="modal-header"><h2 id="titulo-mg2">Registrar ingreso a MG2</h2><button type="button" class="modal-close" data-modal-close aria-label="Cerrar">×</button></div><div class="modal-body"><form method="post" action="/controllers/mg_expedientes.php?accion=mg2" class="mg-modal-form" data-no-ajax="1"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="id_expediente" value="<?=$x['id_expediente']?>"><div class="form-group"><label class="form-label">Fecha</label><input type="date" name="fecha" value="<?=date('Y-m-d')?>" required></div><div class="form-group"><label class="form-label">Resultado MG1</label><input name="resultado" value="Aprobada" required></div><div class="mg-modal-actions"><button type="button" class="btn btn-light" data-modal-close>Cancelar</button><button class="btn btn-primary">Registrar ingreso a MG2</button></div></form></div></div></div><?php endif; ?>
<?php if(tiene_permiso('mg.expedientes.editar')): ?><div class="toolbar" style="margin-top:18px"><div><strong>Estado del expediente</strong><div class="subtitle">Los cambios sensibles quedan registrados en bitácora.</div></div><button type="button" class="btn btn-primary" data-open-modal="#modal-estado-expediente">Cambiar estado</button></div>
<div class="modal" id="modal-estado-expediente" role="dialog" aria-modal="true" aria-labelledby="titulo-estado-expediente"><div class="modal-dialog"><div class="modal-header"><h2 id="titulo-estado-expediente">Cambiar estado del expediente</h2><button type="button" class="modal-close" data-modal-close aria-label="Cerrar">×</button></div><div class="modal-body"><form method="post" action="/controllers/mg_expedientes.php?accion=estado" class="mg-modal-form" data-no-ajax="1"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="id_expediente" value="<?=$x['id_expediente']?>"><div class="form-group"><label class="form-label">Nuevo estado</label><select name="estado"><option <?= $x['estado']==='activo'?'selected':'' ?>>activo</option><option <?= $x['estado']==='aprobado'?'selected':'' ?>>aprobado</option><option <?= $x['estado']==='reprobado'?'selected':'' ?>>reprobado</option><option <?= $x['estado']==='abandono'?'selected':'' ?>>abandono</option><option <?= $x['estado']==='retirado'?'selected':'' ?>>retirado</option></select></div><div class="form-group"><label class="form-label">Motivo</label><input name="motivo" placeholder="Obligatorio para abandono o reprobado"></div><div class="mg-modal-actions"><button type="button" class="btn btn-light" data-modal-close>Cancelar</button><button class="btn btn-primary">Guardar estado</button></div></form></div></div></div><?php endif; ?>
<?php require __DIR__.'/../../layouts/footer.php'; ?>
