<?php require __DIR__.'/../../layouts/header.php'; ?>
<div class="toolbar">
  <div><h1 class="page-title">Expedientes de Modalidades de Grado</h1><p class="subtitle">Listado paginado con filtros por cohorte, modalidad, etapa y estado. Solo estudiantes egresados, con la carrera culminada, pueden iniciar un expediente.</p></div>
  <?php if($puedeCrear): ?><div class="actions"><button type="button" class="btn btn-primary" data-open-modal="#modal-nuevo-expediente"><i class="bi bi-plus-circle" aria-hidden="true"></i> Expediente</button><a class="btn btn-light" href="/controllers/mg_importar.php">Importar CSV</a></div><?php endif; ?>
</div>
<div class="card"><div class="card-body"><form method="get" class="form-grid"><input type="hidden" name="accion" value="listar"><div><label class="form-label">Buscar</label><input name="q" value="<?=e($filtros['q'])?>" placeholder="Nombre o registro"></div><div><label class="form-label">Cohorte</label><select name="id_cohorte"><option value="">Todas</option><?php foreach($cohortes as $c): ?><option value="<?=$c['id_cohorte']?>" <?=$filtros['id_cohorte']==$c['id_cohorte']?'selected':''?>><?=e($c['nombre'])?></option><?php endforeach;?></select></div><div><label class="form-label">Modalidad</label><select name="id_modalidad"><option value="">Todas</option><?php foreach($modalidades as $m): ?><option value="<?=$m['id_modalidad']?>" <?=$filtros['id_modalidad']==$m['id_modalidad']?'selected':''?>><?=e($m['nombre'])?></option><?php endforeach;?></select></div><div><label class="form-label">Etapa</label><select name="etapa_actual"><option value="">Todas</option><?php foreach(['previa','mg1','mg2','finalizado'] as $v): ?><option <?=$filtros['etapa_actual']===$v?'selected':''?>><?=$v?></option><?php endforeach;?></select></div><div><label class="form-label">Estado</label><select name="estado"><option value="">Todos</option><?php foreach(['activo','aprobado','reprobado','abandono','retirado'] as $v): ?><option <?=$filtros['estado']===$v?'selected':''?>><?=$v?></option><?php endforeach;?></select></div><div><button class="btn btn-primary" type="submit">Filtrar</button></div></form></div></div>
<div class="card"><div class="card-body"><div class="table-wrap"><table class="table"><thead><tr><th>Estudiante</th><th>Registro</th><th>Modalidad</th><th>Cohorte</th><th>Etapa</th><th>Estado</th><th>Tutor</th><th></th></tr></thead><tbody><?php foreach($datos['filas'] as $x): ?><tr><td><?=e($x['apellido'].', '.$x['nombre'])?></td><td><?=e($x['registro_universitario'])?></td><td><?=e($x['modalidad_nombre'])?></td><td><?=e($x['cohorte_nombre'])?></td><td><?=e($x['etapa_actual'])?></td><td><?=e($x['estado'])?></td><td><?=e($x['tutor_nombre']??'Sin asignar')?></td><td><a class="btn btn-light btn-sm" href="/controllers/mg_expedientes.php?accion=ficha&id=<?=$x['id_expediente']?>">Ver ficha</a></td></tr><?php endforeach; if(!$datos['filas']): ?><tr><td colspan="8" class="empty compact">No hay expedientes para los filtros seleccionados.</td></tr><?php endif;?></tbody></table></div></div></div>
<?php if($puedeCrear): ?>
<div class="modal mg-modal-wide" id="modal-nuevo-expediente" role="dialog" aria-modal="true" aria-labelledby="titulo-nuevo-expediente"><div class="modal-dialog"><div class="modal-header"><h2 id="titulo-nuevo-expediente">Crear expediente MG</h2><button type="button" class="modal-close" data-modal-close aria-label="Cerrar">×</button></div><div class="modal-body"><form method="post" action="/controllers/mg_expedientes.php?accion=guardar" class="mg-modal-form" data-no-ajax="1"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><div class="grid grid-2"><div class="form-group"><label class="form-label">Estudiante egresado</label><select name="id_estudiante" required><option value="">Selecciona</option><?php foreach($model->estudiantes() as $e): ?><option value="<?=$e['id_estudiante']?>"><?=e(($e['registro_universitario']?:'Sin registro').' - '.$e['apellido'].', '.$e['nombre'].' ('.($e['estado_academico']??'egresado').')')?></option><?php endforeach;?></select><div class="form-help">Solo estudiantes con estado académico egresado debe iniciar MG.</div></div><div class="form-group"><label class="form-label">Modalidad</label><select name="id_modalidad" required><?php foreach($modalidades as $m): ?><option value="<?=$m['id_modalidad']?>"><?=e($m['nombre'])?></option><?php endforeach;?></select></div><div class="form-group"><label class="form-label">Cohorte</label><select name="id_cohorte" required><?php foreach($cohortes as $c): ?><option value="<?=$c['id_cohorte']?>"><?=e($c['nombre'])?></option><?php endforeach;?></select></div><div class="form-group"><label class="form-label">Fecha inicio</label><input type="date" name="fecha_inicio" value="<?=date('Y-m-d')?>" required></div><div class="form-group"><label class="form-label">Título del trabajo</label><input name="titulo_trabajo"></div><div class="form-group"><label class="form-label">Observaciones</label><textarea name="observaciones"></textarea></div></div><div class="mg-modal-actions"><button type="button" class="btn btn-light" data-modal-close>Cancelar</button><button class="btn btn-primary" type="submit">Crear expediente</button></div></form></div></div></div>
<?php endif; ?>
<?php require __DIR__.'/../../layouts/footer.php'; ?>
