<?php
class CalificacionModel
{
    private PDO $pdo;
    function __construct(PDO $pdo){$this->pdo=$pdo;}
    function obtenerTodas(){return $this->pdo->query("SELECT c.*,CONCAT(u.nombre,' ',u.apellido) estudiante,cu.nombre_curso,cu.codigo,CASE WHEN c.tipo LIKE 'Tutoría:%' AND c.nota=0 AND c.fecha<CURDATE() THEN 1 ELSE 0 END vencida FROM calificaciones c JOIN inscripciones i ON i.id_inscripcion=c.id_inscripcion JOIN estudiantes e ON e.id_estudiante=i.id_estudiante JOIN usuarios u ON u.id_usuario=e.id_usuario JOIN cursos cu ON cu.id_curso=i.id_curso ORDER BY vencida DESC,c.fecha DESC,c.id_calificacion DESC")->fetchAll();}
    function obtenerParaDocente(int $idUsuario){$s=$this->pdo->prepare("SELECT c.*,CONCAT(u.nombre,' ',u.apellido) estudiante,cu.nombre_curso,cu.codigo,CASE WHEN c.tipo LIKE 'Tutoría:%' AND c.nota=0 AND c.fecha<CURDATE() THEN 1 ELSE 0 END vencida FROM calificaciones c JOIN inscripciones i ON i.id_inscripcion=c.id_inscripcion JOIN estudiantes e ON e.id_estudiante=i.id_estudiante JOIN usuarios u ON u.id_usuario=e.id_usuario JOIN cursos cu ON cu.id_curso=i.id_curso JOIN profesores p ON p.id_profesor=cu.id_profesor WHERE p.id_usuario=? ORDER BY cu.codigo,u.apellido,u.nombre,c.fecha DESC,c.id_calificacion DESC");$s->execute([$idUsuario]);return $s->fetchAll();}
    function obtenerPorId($id){$s=$this->pdo->prepare('SELECT * FROM calificaciones WHERE id_calificacion=?');$s->execute([$id]);return $s->fetch();}
    function obtenerDetalle($id){$s=$this->pdo->prepare("SELECT c.*,CONCAT(u.nombre,' ',u.apellido) estudiante,cu.nombre_curso,cu.codigo FROM calificaciones c JOIN inscripciones i ON i.id_inscripcion=c.id_inscripcion JOIN estudiantes e ON e.id_estudiante=i.id_estudiante JOIN usuarios u ON u.id_usuario=e.id_usuario JOIN cursos cu ON cu.id_curso=i.id_curso WHERE c.id_calificacion=?");$s->execute([$id]);return $s->fetch();}
    function perteneceADocente(int $idCalificacion,int $idUsuario):bool{$s=$this->pdo->prepare("SELECT COUNT(*) FROM calificaciones c JOIN inscripciones i ON i.id_inscripcion=c.id_inscripcion JOIN cursos cu ON cu.id_curso=i.id_curso JOIN profesores p ON p.id_profesor=cu.id_profesor WHERE c.id_calificacion=? AND p.id_usuario=?");$s->execute([$idCalificacion,$idUsuario]);return (int)$s->fetchColumn()>0;}
    function inscripcionPerteneceADocente(int $idInscripcion,int $idUsuario):bool{$s=$this->pdo->prepare("SELECT COUNT(*) FROM inscripciones i JOIN cursos cu ON cu.id_curso=i.id_curso JOIN profesores p ON p.id_profesor=cu.id_profesor WHERE i.id_inscripcion=? AND p.id_usuario=?");$s->execute([$idInscripcion,$idUsuario]);return (int)$s->fetchColumn()>0;}
    function crear($d){$s=$this->pdo->prepare('INSERT INTO calificaciones(id_inscripcion,tipo,nota,observacion,fecha) VALUES(?,?,?,?,?)');return $s->execute([$d['id_inscripcion'],$d['tipo'],$d['nota'],$d['observacion']??'',$d['fecha']]);}
    function editar($id,$d){$s=$this->pdo->prepare('UPDATE calificaciones SET id_inscripcion=?,tipo=?,nota=?,observacion=?,fecha=? WHERE id_calificacion=?');return $s->execute([$d['id_inscripcion'],$d['tipo'],$d['nota'],$d['observacion']??'',$d['fecha'],$id]);}
    function eliminar($id){$s=$this->pdo->prepare('DELETE FROM calificaciones WHERE id_calificacion=?');return $s->execute([$id]);}
}
