<?php
declare(strict_types=1);
class MgAsignacionTutorModel {
 public function __construct(private PDO $pdo) {}
 public function vigente(int $idExp): ?array { $s=$this->pdo->prepare('SELECT a.*,t.id_tutor,u.nombre,u.apellido,t.especialidad FROM asignaciones_tutor a JOIN tutores t ON t.id_tutor=a.id_tutor JOIN profesores p ON p.id_profesor=t.id_profesor JOIN usuarios u ON u.id_usuario=p.id_usuario WHERE a.id_expediente=? AND a.estado="vigente" LIMIT 1');$s->execute([$idExp]);return $s->fetch()?:null; }
 public function historial(int $idExp): array {$s=$this->pdo->prepare('SELECT a.*,u.nombre,u.apellido,t.especialidad FROM asignaciones_tutor a JOIN tutores t ON t.id_tutor=a.id_tutor JOIN profesores p ON p.id_profesor=t.id_profesor JOIN usuarios u ON u.id_usuario=p.id_usuario WHERE a.id_expediente=? ORDER BY a.fecha_asignacion DESC,a.id_asignacion DESC');$s->execute([$idExp]);return $s->fetchAll();}
 public function tutores(): array { return $this->pdo->query('SELECT t.id_tutor,t.especialidad,u.nombre,u.apellido,(SELECT COUNT(*) FROM asignaciones_tutor a WHERE a.id_tutor=t.id_tutor AND a.estado="vigente") carga,(SELECT COUNT(*) FROM disponibilidad_tutor d WHERE d.id_tutor=t.id_tutor) disponibilidad FROM tutores t JOIN profesores p ON p.id_profesor=t.id_profesor JOIN usuarios u ON u.id_usuario=p.id_usuario ORDER BY u.apellido,u.nombre')->fetchAll(); }
 public function guardar(int $idExp,array $d,?int $idAnterior=null): int { $this->pdo->beginTransaction();try{$s=$this->pdo->prepare('SELECT * FROM expedientes_mg WHERE id_expediente=? FOR UPDATE');$s->execute([$idExp]);$exp=$s->fetch();if(!$exp)throw new RuntimeException('Expediente inexistente.');$s=$this->pdo->prepare('SELECT id_modalidad FROM expedientes_mg WHERE id_expediente=?');$s->execute([$idExp]);$modal=(int)$s->fetchColumn();$s=$this->pdo->prepare('SELECT requiere_tutor FROM modalidades_grado WHERE id_modalidad=?');$s->execute([$modal]);if(!(int)$s->fetchColumn())throw new RuntimeException('Esta modalidad no requiere Tutor.');$s=$this->pdo->prepare('SELECT id_asignacion FROM asignaciones_tutor WHERE id_expediente=? AND estado="vigente" FOR UPDATE');$s->execute([$idExp]);$actual=$s->fetchColumn(); if($actual){ if($idAnterior!==null && (int)$actual===$idAnterior){$s=$this->pdo->prepare('UPDATE asignaciones_tutor SET estado="reemplazada",fecha_fin=?,motivo_fin=?,referencia_decanatura=? WHERE id_asignacion=?');$s->execute([$d['fecha'], $d['motivo_fin']??null,$d['referencia_decanatura']??null,$actual]);} elseif($idAnterior===null) throw new RuntimeException('El expediente ya tiene un Tutor vigente. Use la opción Cambiar Tutor.'); else throw new RuntimeException('La asignación vigente cambió; recargue la ficha.'); }
  $s=$this->pdo->prepare('INSERT INTO asignaciones_tutor(id_expediente,id_tutor,fecha_asignacion,estado,referencia_decanatura,disponibilidad_consultada,observaciones,registrado_por) VALUES(?,?,?,"vigente",?,?,?,?)');$s->execute([$idExp,$d['id_tutor'],$d['fecha'], $d['referencia_decanatura']??null,(int)$d['disponibilidad_consultada'],$d['observaciones']??null,$_SESSION['id_usuario']??null]);$id=(int)$this->pdo->lastInsertId();$this->pdo->commit();return $id;}catch(Throwable $e){if($this->pdo->inTransaction())$this->pdo->rollBack();throw $e;}}
}
