<?php
declare(strict_types=1);
class MgDefensaModel {
 public function __construct(private PDO $pdo) {}
 public function tribunales(int $idExp,string $etapa): array { $s=$this->pdo->prepare('SELECT td.*,u.nombre,u.apellido,t.especialidad FROM tribunales_defensa td JOIN tutores t ON t.id_tutor=td.id_tutor JOIN profesores p ON p.id_profesor=t.id_profesor JOIN usuarios u ON u.id_usuario=p.id_usuario WHERE td.id_expediente=? AND td.etapa=? ORDER BY td.estado DESC,td.orden');$s->execute([$idExp,$etapa]);return $s->fetchAll(); }
 public function tutores(): array { return $this->pdo->query('SELECT t.id_tutor,u.nombre,u.apellido,t.especialidad,(SELECT COUNT(*) FROM asignaciones_tutor a WHERE a.id_tutor=t.id_tutor AND a.estado="vigente") carga FROM tutores t JOIN profesores p ON p.id_profesor=t.id_profesor JOIN usuarios u ON u.id_usuario=p.id_usuario ORDER BY u.apellido,u.nombre')->fetchAll(); }
 public function asignar(int $idExp,string $etapa,array $ids): void { $this->pdo->beginTransaction();try{$s=$this->pdo->prepare('SELECT id_expediente FROM expedientes_mg WHERE id_expediente=? FOR UPDATE');$s->execute([$idExp]);if(!$s->fetchColumn())throw new RuntimeException('Expediente inexistente.');$s=$this->pdo->prepare('UPDATE tribunales_defensa SET estado="reemplazado" WHERE id_expediente=? AND etapa=? AND estado="vigente"');$s->execute([$idExp,$etapa]);$ins=$this->pdo->prepare('INSERT INTO tribunales_defensa(id_expediente,etapa,id_tutor,orden,fecha_asignacion,registrado_por) VALUES(?,?,?,?,?,?)');$hoy=date('Y-m-d');foreach(array_values($ids) as $i=>$id){$ins->execute([$idExp,$etapa,(int)$id,$i+1,$hoy,$_SESSION['id_usuario']??null]);}$this->pdo->commit();}catch(Throwable $e){if($this->pdo->inTransaction())$this->pdo->rollBack();throw $e;}}
 public function defensas(array $f=[]): array { $w=[];$p=[];if(!empty($f['fecha'])){$w[]='d.fecha=?';$p[]=$f['fecha'];}if(!empty($f['id_expediente'])){$w[]='d.id_expediente=?';$p[]=(int)$f['id_expediente'];}if(!empty($f['id_usuario_estudiante'])){$w[]='e.id_usuario=?';$p[]=(int)$f['id_usuario_estudiante'];}if(!empty($f['id_usuario_tutor'])){$w[]='p.id_usuario=?';$p[]=(int)$f['id_usuario_tutor'];}$where=$w?' WHERE '.implode(' AND ',$w):'';$s=$this->pdo->prepare('SELECT d.*,x.id_expediente,e.registro_universitario,u.nombre,u.apellido,m.nombre modalidad_nombre,c.nombre cohorte_nombre FROM defensas_mg d JOIN expedientes_mg x ON x.id_expediente=d.id_expediente JOIN estudiantes e ON e.id_estudiante=x.id_estudiante JOIN usuarios u ON u.id_usuario=e.id_usuario JOIN modalidades_grado m ON m.id_modalidad=x.id_modalidad JOIN cohortes_mg c ON c.id_cohorte=x.id_cohorte LEFT JOIN asignaciones_tutor a ON a.id_expediente=x.id_expediente AND a.estado="vigente" LEFT JOIN tutores t ON t.id_tutor=a.id_tutor LEFT JOIN profesores p ON p.id_profesor=t.id_profesor'.$where.' ORDER BY d.fecha,d.hora_inicio');$s->execute($p);return $s->fetchAll();}
 public function choque(int $idDefensa,string $fecha,string $ini,string $fin,string $ambiente,array $tribunales,int $idExp): ?string { $s=$this->pdo->prepare('SELECT COUNT(*) FROM defensas_mg WHERE fecha=? AND estado IN ("programada","realizada","reprogramada") AND id_defensa<>? AND hora_inicio < ? AND hora_fin > ? AND ambiente=?');$s->execute([$fecha,$idDefensa,$fin,$ini,$ambiente]);if((int)$s->fetchColumn()>0)return 'El ambiente ya está ocupado en ese horario.';if($tribunales){$s=$this->pdo->prepare('SELECT d.id_defensa FROM defensas_mg d JOIN tribunales_defensa td ON td.id_expediente=d.id_expediente AND td.etapa=d.etapa WHERE d.fecha=? AND d.estado IN ("programada","realizada","reprogramada") AND d.id_defensa<>? AND d.hora_inicio < ? AND d.hora_fin > ? AND td.estado="vigente" AND td.id_tutor IN ('.implode(',',array_fill(0,count($tribunales),'?')).') LIMIT 1');$params=array_merge([$fecha,$idDefensa,$fin,$ini],array_map('intval',$tribunales));$s->execute($params);if($s->fetchColumn())return 'Uno de los tribunales ya tiene otra defensa en ese horario.';}$s=$this->pdo->prepare('SELECT COUNT(*) FROM defensas_mg WHERE fecha=? AND estado IN ("programada","realizada","reprogramada") AND id_defensa<>? AND id_expediente=? AND hora_inicio < ? AND hora_fin > ?');$s->execute([$fecha,$idDefensa,$idExp,$fin,$ini]);if((int)$s->fetchColumn()>0)return 'El estudiante ya tiene otra defensa en ese horario.';return null;}
 public function guardarDefensa(array $d): int { $s=$this->pdo->prepare('INSERT INTO defensas_mg(id_expediente,etapa,fecha,hora_inicio,hora_fin,ambiente,estado,obs_fondo,obs_forma,autorizado_por,referencia_autorizacion) VALUES(?,?,?,?,?,?,?,?,?,?,?)');$s->execute([$d['id_expediente'],$d['etapa'],$d['fecha'],$d['hora_inicio'],$d['hora_fin'],$d['ambiente'],$d['estado'],$d['obs_fondo']?:null,$d['obs_forma']?:null,$d['autorizado_por']?:null,$d['referencia_autorizacion']?:null]);return (int)$this->pdo->lastInsertId();}
 public function obtener(int $id): ?array {$s=$this->pdo->prepare('SELECT d.*,x.id_estudiante,e.id_usuario id_usuario_estudiante,u.nombre,u.apellido,m.nombre modalidad_nombre,c.nombre cohorte_nombre FROM defensas_mg d JOIN expedientes_mg x ON x.id_expediente=d.id_expediente JOIN estudiantes e ON e.id_estudiante=x.id_estudiante JOIN usuarios u ON u.id_usuario=e.id_usuario JOIN modalidades_grado m ON m.id_modalidad=x.id_modalidad JOIN cohortes_mg c ON c.id_cohorte=x.id_cohorte WHERE d.id_defensa=?');$s->execute([$id]);return $s->fetch()?:null;}
 public function calificacion(int $id): ?array {$s=$this->pdo->prepare('SELECT * FROM calificaciones_mg WHERE id_defensa=?');$s->execute([$id]);return $s->fetch()?:null;}
 public function guardarCalificacion(int $idDef,float $nota,string $obs,int $publicada): void {$s=$this->pdo->prepare('INSERT INTO calificaciones_mg(id_defensa,nota,observaciones,publicada,registrada_por) VALUES(?,?,?,?,?) ON DUPLICATE KEY UPDATE nota=VALUES(nota),observaciones=VALUES(observaciones),publicada=VALUES(publicada),registrada_por=VALUES(registrada_por),fecha_registro=CURRENT_TIMESTAMP');$s->execute([$idDef,$nota,$obs?:null,$publicada,$_SESSION['id_usuario']??null]);}
 public function promedio(int $idExp): ?float {$s=$this->pdo->prepare('SELECT AVG(c.nota) FROM calificaciones_mg c JOIN defensas_mg d ON d.id_defensa=c.id_defensa WHERE d.id_expediente=?');$s->execute([$idExp]);$v=$s->fetchColumn();return $v===null?null:(float)$v;}
}
