<?php
declare(strict_types=1);
class MgImportacionModel {
 public function __construct(private PDO $pdo) {}
 public function validarFilas(array $filas): array {
  $modalidades=$this->pdo->query('SELECT id_modalidad,codigo,nombre FROM modalidades_grado WHERE activa=1')->fetchAll(); $m=[]; foreach($modalidades as $r){$m[strtolower($r['codigo'])]=$r;$m[strtolower($r['nombre'])]=$r;}
  $cohortes=$this->pdo->query('SELECT id_cohorte,codigo,nombre FROM cohortes_mg WHERE activa=1')->fetchAll(); $c=[]; foreach($cohortes as $r){$c[strtolower($r['codigo'])]=$r;$c[strtolower($r['nombre'])]=$r;}
  $out=[]; foreach($filas as $i=>$r){$n=$i+2;$msg=[];$resultado='ok'; $registro=trim((string)($r['registro_universitario']??'')); $modal=trim((string)($r['modalidad']??'')); $coh=trim((string)($r['cohorte']??''));
   $est=null; if($registro===''){ $resultado='error';$msg[]='Falta registro_universitario'; } else {$s=$this->pdo->prepare('SELECT e.id_estudiante,e.id_usuario,u.nombre,u.apellido,e.estado_academico FROM estudiantes e JOIN usuarios u ON u.id_usuario=e.id_usuario WHERE e.registro_universitario=?');$s->execute([$registro]);$est=$s->fetch(); if(!$est){$resultado='pendiente_cuenta';$msg[]='No existe una cuenta de estudiante con ese registro universitario.';} elseif(!in_array($est['estado_academico'],['egresado','titulado'],true)){ $resultado='error';$msg[]='El estudiante aún no figura como egresado/titulado y no puede iniciar modalidad de grado.';}}
   $mo=$m[strtolower($modal)]??null; if(!$mo){$resultado='error';$msg[]='Modalidad inexistente o inactiva.';}
   $co=$c[strtolower($coh)]??null; if(!$co){$resultado='error';$msg[]='Cohorte inexistente o inactiva.';}
   if($est&&$mo&&$co){$s=$this->pdo->prepare('SELECT id_expediente FROM expedientes_mg WHERE id_estudiante=? AND id_modalidad=? AND id_cohorte=?');$s->execute([$est['id_estudiante'],$mo['id_modalidad'],$co['id_cohorte']]); if($s->fetchColumn()){ $resultado='advertencia';$msg[]='El expediente ya existe; se omitirá al confirmar.'; }}
   $out[]=['fila'=>$n,'datos'=>$r,'resultado'=>$resultado,'mensaje'=>implode(' ',$msg),'id_estudiante'=>$est['id_estudiante']??null,'id_modalidad'=>$mo['id_modalidad']??null,'id_cohorte'=>$co['id_cohorte']??null];
  } return $out;
 }
 public function confirmar(array $validaciones,string $archivo): array { $this->pdo->beginTransaction(); try{$s=$this->pdo->prepare('INSERT INTO importaciones_mg(archivo,usuario,total_filas) VALUES(?,?,?)');$s->execute([$archivo,$_SESSION['id_usuario']??null,count($validaciones)]);$imp=(int)$this->pdo->lastInsertId();$ok=$adv=$err=0; foreach($validaciones as $v){$idExp=null;$res=$v['resultado']; if(in_array($res,['ok','advertencia'],true)&&$v['id_estudiante']&&$v['id_modalidad']&&$v['id_cohorte']){ $s=$this->pdo->prepare('SELECT id_expediente FROM expedientes_mg WHERE id_estudiante=? AND id_modalidad=? AND id_cohorte=?');$s->execute([$v['id_estudiante'],$v['id_modalidad'],$v['id_cohorte']]); if(!$s->fetchColumn()){ $s=$this->pdo->prepare('INSERT INTO expedientes_mg(id_estudiante,id_modalidad,id_cohorte,fecha_inicio) VALUES(?,?,?,?)');$s->execute([$v['id_estudiante'],$v['id_modalidad'],$v['id_cohorte'],date('Y-m-d')]);$idExp=(int)$this->pdo->lastInsertId();$s=$this->pdo->prepare('INSERT INTO expediente_etapas(id_expediente,etapa,fecha_inicio,registrado_por) VALUES(?,"previa",?,?)');$s->execute([$idExp,date('Y-m-d'),$_SESSION['id_usuario']??null]);$ok++;}else{$res='omitido';$adv++;}}
    if($res==='error')$err++; elseif($res==='pendiente_cuenta')$adv++;
    $d=$v['datos'];$s=$this->pdo->prepare('INSERT INTO importaciones_mg_detalle(id_importacion,numero_fila,registro_universitario,nombres,apellidos,resultado,mensaje,datos,id_expediente) VALUES(?,?,?,?,?,?,?,?,?)');$s->execute([$imp,$v['fila'],trim((string)($d['registro_universitario']??'')),trim((string)($d['nombres']??'')),trim((string)($d['apellidos']??'')),$res,$v['mensaje']?:null,json_encode($d,JSON_UNESCAPED_UNICODE),$idExp]); }
    $s=$this->pdo->prepare('UPDATE importaciones_mg SET total_ok=?,total_advertencias=?,total_errores=? WHERE id_importacion=?');$s->execute([$ok,$adv,$err,$imp]);$this->pdo->commit();return ['id'=>$imp,'ok'=>$ok,'advertencias'=>$adv,'errores'=>$err]; }catch(Throwable $e){if($this->pdo->inTransaction())$this->pdo->rollBack();throw $e;}}
}
